version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=*123qwe*
      - MYSQL_DATABASE=chatdb
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=*123qwe*
    ports:
      - "3306:3306"

volumes:
  mysql_data: